# Generated by Django 2.1.7 on 2019-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.DecimalField(decimal_places=0, default=False, max_digits=2),
        ),
    ]
